name: Run tests and apply terraform changes for current branch

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test with SBT
        run: |
          ./scripts/test

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/scala-2.12/coverage-report/cobertura.xml

      - name: Run CodeCOV action
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/scala-2.12/coverage-report/cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false

#      - name: Build with ASSEMBLY
#        run: |
#          ./scripts/build
